### ISSUE TITLE
No config-form after plugin installation

### ISSUE THREAD

**Issue by tloehr** [kanboard/plugin-jabber#1]
Installed all the files unter plugins/jabber. The plugin is displayed on kanboard under "settings -> plugins".
But there is no config webform under "settings -> integration". What am I doing wrong ?

Thanks.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
