### ISSUE TITLE
Notifications to a room

### ISSUE THREAD

**Issue by risturiz** [kanboard/plugin-jabber#6]
Hi, i have xmpp plugin working.. But i cant see the message on MUC, the user only join/part from room without leaving any link to task... Direct notification from xmpp works to my user

> Application version: 1.0.43
> PHP version: 5.6.30-0+deb8u1
> PHP SAPI: fpm-fcgi
> OS version: Linux 2.6.32-44-pve
> Database driver: postgres
> Database version: 9.4.12

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
